# fly.toml app configuration file generated for dialog-video-gen on 2025-08-18T23:54:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bytemeguyguy'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
